version: '3'
services: 
  app-mirval-basic:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
    stdin_open: true